- index.html
> Added doctype decleration to index.html

- styles/styles.css
Styles for hero-unit heading on small screens
> Added responsive styles for .hero-unit with heading on screen < 480px

- index.html
- js/index.js
Adds #7, random boards to the project cards. Everything added is contained within the ` $(".border-fade").each` in `index.js`. Aside from the script tag getting the random color library for this.
> Add random borders to project cards

- js/index.js
> Arrange card based on latest activity first

- js/index.js
> Added label for Language in the repo box

- index.html
- styles/styles.css
Fix header navbar to align with the page structure #34
> navbar alignment fixed, and intro text positioning

- index.html
> Header Text Spelling mistake fixed

- pages/gsoc/index.html
- pages/template.html
> Added Inner pages structure, created a base template. GSoC page Created

- config.json
- js/index.js
> Updated config and gsoc child page directory from index.js

- index.html
- pages/gsoc/index.html
- pages/template.html
> Added Analytics to inner pages and to the page template

- js/index.js
- styles/styles.css
> Added missing language labels 

- js/index.js
> Replace null value with user friendly text #101

- styles/styles.css
* Updated the item title text overflow to be breaked into lines
* Set the max width of the item to be 100% to avoid going overflow
This fixes #97
> gh-97: Updated the .item styles to fit into the small screen sizes

- index.html
- js/index.js
- styles/styles.css
@rehrumesh @charithsoori @chamathpali 
this closes #3
> gh-3: Added an interface to list down activities of the repositories

- index.html
- js/index.js
- styles/styles.css
This is being taken with #99 since that's also a part of this customization
This fixes #107 
**Here are few screenshots in different sizes**
> gh-107: Fixing the issues in the grid of repositories

- js/index.js
This closes #116 
Now if the time is less than a day
it will display
xx minutes ago, xx hours ago etc.
> Added xx times ago type display

- LICENSE.md
> Fixes #91 - Added LICENSE.md

- js/index.js
- styles/styles.css
> Added Python Language label

- index.html
- styles/styles.css
> Fix the preloader gif issue

- index.html
- js/index.js
Reverts 99xt/99xt.github.io#88
> Adding GSoC link again

- pages/gsoc/projects/partials/tabs/projects.html
Adding click here button to projects
> add-button

- pages/gsod/projects/data/projects.js
- pages/gsod/projects/data/projects/serverless-react.md
- Updated the serverless-react description for GSoD section of the page
> Update serverless-react description for GsoD

- pages/gsod/projects/data/projects.js
- pages/gsod/projects/data/projects/serverless-react.md
> quick fixes to serverless-react desc
